- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINSR9AJBpixGPZGgNFAR5qbc7IZCdX0b35Lp5f/CUFhs ansible"

- name: genetrate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
  notify: restart_sshd
   
